### ISSUE TITLE
Review road data from Translink

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#129]
Review road data from Translink  (e.g., turn restrictions, truck routes, height/weight/width restrictions) to understand their schema and data better.

**Comment by gleeming** [comment]
The CVRP data was supplied by Translink as a TAR/ZIP of a PostGIS export with a very limited data dictionary.  It was loaded into a database and the single trfinal line layer was then extracted to a shapefile for review.  The geometry is based on a vintage of ITN and encompasses both demographic and non-demographic roads.  Most of the attributes from the ITN are preserved and at times uses codes rather than the full descriptors (ie. rd_class).

The data also contains an additional set of Translink business attributes which have been conflated or integrated onto the ITN base.  These include travel times/costs, truck route types, restrictions, temporary impactors/notices, ferry or border crossings.  Here are some example attributes
- truckroute_id: unique id for each truck route segment
- truck_definition_weight: the weight threshold where vehicles are considered a truck and must comply with truck route bylaws
- restricted: flag to indicate a restriction, with values of 0, 1, 2
- type_tr: type of truck route
- max_weight: the maximum vehicle weight that is permitted to travel on this segment
- max_height: the maximum vehicle height that is permitted to travel on this segment
- rest: Long description of restriction

**Comment by mraross** [comment]
Verified
