### ISSUE TITLE
Turn restrictions not getting applied on an overpass

### ISSUE THREAD

**Issue by gleeming** [bcgov/ols-router#138]
There is an intersection where a restricted class road crosses over a trail and is blocked by barriers.  After adding turn restrictions to model no through traffic across the height separated segments, the router doesn't load them properly.

**Comment by cmhodgson** [comment]
This has been fixed and tested locally.

**Comment by cmhodgson** [comment]
Graeme can you recall where this location was to test this in delivery now? Otherwise I'm going to call it confirmed as I did test it locally when I originally fixed it. The restrictions related to the barricade should now be automatically generated, and work properly across under/overpass cases such as this.

**Comment by gleeming** [comment]
Belmont Rd and Galloping Goose Trail in Colwood.  It looks like it may not be working properly

**Comment by mraross** [comment]
Verified
