### ISSUE TITLE
rest endpoint for admin app export and import config file

### ISSUE THREAD

**Issue by ll911** [bcgov/ols-router#175]
**Is your feature request related to a problem? Please describe.**
add clear restful endpoint for admin app export and import config file

**Describe the solution you'd like**
export config to json 
`curl -X GET ${ADMIN_ENDPOINT}/config -H "Authorization: Bearer Token"
import from json`

`curl -X POST ${ADMIN_ENDPOINT}/config -H "Authorization: Bearer Token" -H "Accept: application/json" -d @fileconfig.json`

**Comment by cmhodgson** [comment]
This should work now except that:
- instead of one restful endpoint it is two separate ones named import and export, and
-  you have to use -F instead of -d because it is setup to work with an upload form so a form-multi-part-encoded mime type is needed. 
Not sure what the Accept header is for, unless you want back a status in json? I guess the restier way would be to use -d with a -H "Content-type: application/json" header, maybe that was what you meant.

**Comment by ll911** [comment]
correct.

**Comment by dkelsey** [comment]
closing.  However the import does not work correctly see: #322
