### ISSUE TITLE
In functional router, add support for time-dependent turn restrictions

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#22]
@mraross commented on [Tue Mar 06 2018](https://github.com/bcgov/api-specs/issues/306)

Take time-dependent and time-independent turn restrictions into account when computing best route.
Turn restrictions are often conditional as in No Left Turn 4 PM - 6PM weekdays

Time-independant turn restrictions are sourced from the BC Digital Road Atlas

**Comment by cmhodgson** [comment]
Do you have any input on the name or format to use for the "departureTime" parameter? Google API calls it "departure_time" and uses the epoch seconds value, this seems reasonable to me, but is not human-friendly. Individual values like departureDay/-Month/-Year/-Hour/-Minute are more human friendly but then you have a lot of parameters, supporting actual date/time strings gets messy with parsing M/d/Y vs Y-M-D vs ???

**Comment by mraross** [comment]
We could follow Here's example:

`Time when travel is expected to start. You can use now to specify the current time. Specify either departure or arrival, not both. Type: xs:dateTime. When the optional timezone offset is not specified time is assumed to be local`

`departure=2013-07-04T17:00:00+02`

so departure=now is also supported and could be the default.

Here also supports arrival with the same syntax.


Source: https://developer.here.com/documentation/routing/topics/resource-calculate-route.html

**Comment by hleckenb** [comment]
Good question. Human centred design would have us providing a calendar picker for dates and drop downs for hour/minute/am or pm. Where the default would be calculated from now, otherwise likely pick could be by time of day then by which day. Interesting question here is … if a person is planning a trip in another time zone, do the settings calculate in their time or the correct time of the locale? Looking at Google and TomTom I notice they only offer timed distance from one point to the next.

Ideally the user would be able to route plan from departure time OR arrival time.

**Comment by mraross** [comment]
Done
