### ISSUE TITLE
Gaps in truck routes on Mt Seymour Parkway and in Maple Ridge

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#245]
2590 Badger Rd, District of North Vancouver, BC
4488 Indian River Dr, District of North Vancouver, BC

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/3fdb70b7-0539-4f8c-984e-4062da8188a7)

Reverse direction goes the long way around because of gap in truck route on Mt Seymour Pkwy
![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/a9590edd-9fc9-4f1e-9d15-92f254336a03)

@gk-tl Please review

**Comment by mraross** [comment]
13197 232 St, Maple Ridge, BC
11555 225 St, Maple Ridge, BC

![image](https://user-images.githubusercontent.com/11318574/77259711-b8a8d300-6c40-11ea-83d8-0ff1bdc57116.png)

**Comment by gk-tl** [comment]
Thanks Michael. 

**Regarding Mt Seymour Parkway:** 

Confirming that Mt. Seymour Parkway WESTBOUND (uphill) should be part of the TRN (no dotted red line). However, EASTBOUND (downhill) has a weight restriction as per TRP cartographic layer (see below). Hence, reverse direction is correct.

![image](https://user-images.githubusercontent.com/59627982/77268354-da1ab680-6c62-11ea-9646-0db6f76ae605.png)

**Regarding Maple Ridge:**
The generated route is non-compliant. See below for correct route.

![image](https://user-images.githubusercontent.com/59627982/77269248-865d9c80-6c65-11ea-8434-fa4e007317a9.png)

**Comment by mraross** [comment]
Thanks Greg. We will tune the machine appropriately.

**Comment by gleeming** [comment]
This is a bit of an extreme case that would either need a multiplier of 21 or higher, or to add many LDFs along all of the north/south connecting roads between Lougheed Hwy and Dewdney Trunk Rd.  There are probably a few other cases similar to this and neither option seems great.

Perhaps instead of continually applying custom tuning for each scenario like this that is discovered (which requires app restarts), we could design a smart truck mode routing approach.  Not sure how possible/easy it would be to implement, but suppose a truck route is generated with a non-standard partition signature -- don't return that and instead double the multiplier and try generating a new route.

The app could even iterate like this until the signature is clean or a threshold (multiplier or number of attempts) is exceeded.  Hypothetically in this case two iterations would take the multiplier from 9 up to 18 then 36, at which point a compliant route would be returned.  It don't think this compliance mode would be triggered very often, but when it does, there would be good chance of an acceptable route being returned (or in some rare cases still remain impossible to be compliant).

**Comment by gk-tl** [comment]
There might an alternative approach - for the 5 municipalities that do not designate truck routes (yellow lines, Maple Ridge being one of them), all roads are truck routes (unless there a posted truck restriction). Routing on the yellow lines, which we are treating as "equivalent" the the TRN, is not mandatory. So while the route is not compliant with municipal preferences, it is not breaking a bylaw. What I'm getting at is that we could show the route as a blue line (i.e., a potential route). Not sure if that makes things easier, but it's another approach.

**Comment by mraross** [comment]
Or we could just develop a tool to apply a local distortion field to all non-truck routes in an area.

**Comment by gk-tl** [comment]
My thought is to check with maple Ridge about adding Laity Street and 227 St or 228 St as a yellow lines (perhaps also 222 St).

**Comment by cmhodgson** [comment]
Just looking around the area and 224 st might be another option, it is a larger divided road and appears to be the primary truck access to Haney Place Mall based on the position of the loading ramps.

**Comment by gk-tl** [comment]
224 Street goes right through the City centre and hs undergone a road diet to make it more ped friendly.

![image](https://user-images.githubusercontent.com/59627982/77481498-05c3ab00-6de1-11ea-86d8-fd333a3f5177.png)

**Comment by mraross** [comment]
Good to know.

**Comment by mraross** [comment]
Greg has identified additional truck routes in https://github.com/bcgov/smk-tlink/issues/119

**Comment by gleeming** [comment]
I added LDF factors on 9 Mt. Seymour Pky segments -- the southern red line in the first image of this ticket.  I have also posted a ticket to GeoBC for them to tag 52 Maple Ridge segments as truck routes.  These are the cases identified by Greg in bcgov/smk-tlink#119.

For both updates they will become active next month in the May-based data release.

**Comment by gk-tl** [comment]
Thanks Graeme. Much appreciated.

**Comment by mraross** [comment]
Verified in delivery with May 2020 data:

![image](https://user-images.githubusercontent.com/11318574/82836981-a8011d00-9e7c-11ea-9a4a-6fdf67957279.png)

**Comment by mraross** [comment]
Verified in delivery with May 2020 data:

![image](https://user-images.githubusercontent.com/11318574/82837317-8ce2dd00-9e7d-11ea-9975-68797c73ea38.png)
