### ISSUE TITLE
possible gap in truck route along Fraser in Surrey

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#248]
9873 182A St, Surrey, BC
19001 Golden Ears Way, Surrey, BC

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/52cc0919-750f-44e9-ab35-aae35bdee649)

**Comment by mraross** [comment]
@gk-tl Please review

**Comment by gk-tl** [comment]
192 Street is not a truck route. Route should be via 96 Ave Connector/Golden Ears Way, not 96 Ave.

![image](https://user-images.githubusercontent.com/59627982/77473139-3ea85380-6dd2-11ea-8bb5-801031ebfac1.png)

**Comment by gk-tl** [comment]
https://www.surrey.ca/files/trnTruckRouteNetwork.pdf

**Comment by gk-tl** [comment]
Correct route generated in reverse direction:

![image](https://user-images.githubusercontent.com/59627982/77475185-a3b17880-6dd5-11ea-8aa1-91225c9c0c36.png)

**Comment by cmhodgson** [comment]
This is because the destination is on the westbound side of the divide on golden ears way. Crank the truck route multiplier up to 20 to see the route necessary to get to that side of golden ears way from that starting point, without leaving the truck route network in between. Realistically though, there is nothing located at that location anyway.

**Comment by mraross** [comment]
Verified as user misunderstanding.
