### ISSUE TITLE
Update South Shore access

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#258]
@gk-tl Please complete this description

**Comment by gk-tl** [comment]
Further to information/input provided courtesy of the Port:

- South shore access should be via Commissioner Street, which is the primary entrance for all commercial vehicles  -  this includes commercial vehicles with drivers not holding a valid port pass.

- Due to the Centerm construction project, this is currently the only commercial vehicle ENTRANCE for the South Shore.

- Commissioner Street and Clark are available for exit.

- Clark Drive entrance (northbound) is currently restricted to passenger vehicles and commercial vehicles 5 tons or less. For the purposes of the TRP, this translates into a weight restriction of 5,000 kg for all northbound vehicles (i.e., same as the weight restricted routes on the North Shore)

- Heatley Ave. entrance is anticipated to be permanently closed late Fall 2020. Until then, for the purposes of the TRP, please put a 5,000 kg weight restriction northbound and southbound between Powell Street and Centennial Road.

See attached file for more info re. Heatley Ave and Clark Drive O/Ps
[2020-03-30 Port South Shore Access.pdf](https://github.com/bcgov/ols-router/files/4407363/2020-03-30.Port.South.Shore.Access.pdf)

**Comment by gleeming** [comment]
Submitted a JIRA ticket for GeoBC to update directional max weight restrictions on 13 segments of Clark Dr and Heatley Ave.

**Comment by gk-tl** [comment]
Thanks Graeme. Much appreciated.

**Comment by mraross** [comment]
Verified in test
