### ISSUE TITLE
Best route takes an extra loop between 49.34905,-123.23019 and 4711 Woodley Dr, West Vancouver, BC

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#281]
49.34905,-123.23019
4711 Woodley Dr, West Vancouver, BC

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/c9034377-a183-4733-a1c6-7aa84225efaf)

**Comment by mraross** [comment]
This didn't happen previously when truck route multiplier was set to 9.

**Comment by gleeming** [comment]
I'm not really clear on how this is an "extra" loop since it is analogous to staying longer on a truck route to skirt a non truck route section.  The first route uses perhaps 50% less non-truck route in its end-to-end path since it doesn't require any travel on Westport Rd.

So from one perspective that is a positive outcome.  TransLink has mentioned that ideally the non-truck route portions at the start and end should take the shortest path to the nearest truck route.  We try to approximate that using LDF, GDF and truck multipliers that model the fastest route, and hope that in the majority of cases the outcome is acceptable.

It would be interesting to hear if TransLink has a preference of one route over the other and can provide a comment.

**Comment by mraross** [comment]
@gk-tl: Greg, could you please indicate your preference of truck route?

**Comment by gk-tl** [comment]
Preference would be to take Exit 4 to Woodgreen Drive/Headland Drive rather than doing a long loop via Hwy 1. I suspect the reason the router generates the other other route is that the ramps are not classified as a truck route for the first route, but are classified as a truck route for the second route. While I recognize this will create a "dangler", it should help generate the correct route.

@al-tabb please update the cartographic data for the Westport on/off ramp (westbound) and the Headlands on/off ramp (eastbound). The Headlands ramps are already classified as a truck route in the router data, but not the cartographic data.

![image](https://user-images.githubusercontent.com/59627982/82976336-aa09cf80-9f93-11ea-91ec-e7c960779258.png)

![image](https://user-images.githubusercontent.com/59627982/82976592-5b106a00-9f94-11ea-9e5d-7d8d7e11cc47.png)

**Comment by gk-tl** [comment]
@al-tabb, @mraross, @gleeming please note I made a couple of edits to my original response. Hopefully it's a little clearer.

**Comment by gleeming** [comment]
Last month I added truck routes to the Headland Dr ramps based on our general rule that it facilitates eastbound highway traffic skirting the overpass.  I had not done the same for Westport Rd ramps because, as per the rule, they are not in a configuration to support a similar maneuver (or link into another truck route).
However I'll create an ITN ticket to get the Westport Rd ramp cases associated with truck routes to support this special case. Hopefully that will be sufficient for the router to avoid the long loop.

**Comment by mraross** [comment]
@gk-tl  Thanks for the quick response Greg. We're getting there faster, one dangler at a time.

**Comment by gk-tl** [comment]
> @gk-tl @al-tabb last month I added truck routes to the Headland Dr ramps based on our general rule that it facilitates eastbound highway traffic skirting the overpass. I had not done the same for Westport Rd ramps because, as per the rule, they are not in a configuration to support a similar maneuver for westbound traffic (or link into another truck route).
> However I'll create an ITN ticket to get the Westport Rd ramp cases associated with truck routes to support this special case. Hopefully that will be sufficient for the router to avoid the long loop.

Thanks Graeme. I know it's not entirely consistent with the general rule we agreed on for highway ramps, but in this case it should help with the routing and hopefully is OK with everyone.

**Comment by mraross** [comment]
Verified in production
