### ISSUE TITLE
Extend visualization to support pop-up restriction attributes that can be copied to clipboard

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#71]
When copying to clipboard, use CSV format and the schema used by the ITN road prep app.

**Comment by cmhodgson** [comment]
What kind of restrictions are you talking about? I guess you must mean turn restrictions... I would have to add the ITN segment Ids to the router (it doesn't know about them now). And copying them won't be of any use as you won't be able to remove them by having a copy of them (especially since the broken ones won't come from the CSV, they will come from ITN). And it would be impossible to work backwards from the in-memory restriction data to an ITN-style turn restriction as the "left-center-right" resolution is not reliably reversible. 
What is the actual goal of this?

**Comment by mraross** [comment]
Its item 10 from sprint 4 in your work plan as follows:

Extend visualization layer so that clicked restriction attribute info can be shown to a user and potentially be copied as a CSV row modeled like our restriction input file (with edge|node|edge values, etc)

**Comment by mraross** [comment]
not needed
