### ISSUE TITLE
Develop a test framework that allows route planner results to be compared to benchmarks across multiple versions

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#77]
1. Define a csv format for route requests and their responses.

2. Write a script that takes a list of route requests in RPNG test format and executes them against the current route planner, and creates a list of route responses.

3.  Write a script that takes a list of route responses, compares the responses to a list of benchmark route responses and produces a report of the differences.

4. Write a javascript app that allows interactive test case management as follows:

    a. Create and submit a route test case

    b. Compare resulting route of latest run to a benchmark route result

    c.  Set a given route result as a benchmark of a given test case.

    d.  Take a list of test cases and submit them to the route planner then compare the resulting routes to benchmark route results.

The test cases and benchmarks should ideally be stored in the ols_router repository

**Comment by cmhodgson** [comment]
We have developed a database-driven testing framework for our use. This ticket as written is about a framework that can be included in the open source code and would be usable by anyone who downloaded the code and wanted to test the router and also for potential open source contributors. While this is still a desirable goal, it wasn't our target for M4.

**Comment by mraross** [comment]
Verified

**Comment by gleeming** [comment]
Our dev test framework is built on FME, Postgres/PostGIS, PHP and Leaflet.  It supports the following features/functionality:
- generated test cases with parameters that can be set at run-time (to observe impacts of different settings)
- custom test cases with fixed parameters to support repeatable runs (regression testing)
- tagging test runs to releases and data vintages, forward and backward directions
- automated recording of responses to provide a history of run results, either in test mode (vs RouterNG code) or against another router (e.g. BC Gov, Google)
- setting a forward and reverse result that represents the expected response for each custom test
- a PHP web UI that can:
  1. display test parameters, runs, results, history, differences
  2. calculate and summarize test variances (particularly distance and calculation time) between runs or reference sets
  3. show route comparison cases in a web map

The full suite of forward and backward tests have been run and analyzed for every release of RouterNG code or data input change since the first working build.
